# AND Perceptron

In [16]:
import pandas as pd

# TODO: Set weight1, weight2, and bias
weight1 = 1.0
weight2 = 1.0
bias = -1.5


# DON'T CHANGE ANYTHING BELOW
# Inputs and outputs
test_inputs = [(0, 0), (0, 1), (1, 0), (1, 1)]
correct_outputs = [False, False, False, True]
outputs = []

# Generate and check output
for test_input, correct_output in zip(test_inputs, correct_outputs):
    linear_combination = weight1 * test_input[0] + weight2 * test_input[1] + bias
    output = int(linear_combination >= 0)
    is_correct_string = 'Yes' if output == correct_output else 'No'
    outputs.append([test_input[0], test_input[1], linear_combination, output, is_correct_string])

# Print output
num_wrong = len([output[4] for output in outputs if output[4] == 'No'])
output_frame = pd.DataFrame(outputs, columns=['Input 1', '  Input 2', '  Linear Combination', '  Activation Output', '  Is Correct'])
if not num_wrong:
    print('Nice!  You got it all correct.\n')
else:
    print('You got {} wrong.  Keep trying!\n'.format(num_wrong))
print(output_frame.to_string(index=False))


Nice!  You got it all correct.

Input 1    Input 2    Linear Combination    Activation Output   Is Correct
      0          0                  -1.5                    0          Yes
      0          1                  -0.5                    0          Yes
      1          0                  -0.5                    0          Yes
      1          1                   0.5                    1          Yes


# NOT Perceptron

In [53]:
import pandas as pd

# TODO: Set weight1, weight2, and bias
weight1 = 0.25
weight2 = -0.26
bias = 0.0


# DON'T CHANGE ANYTHING BELOW
# Inputs and outputs
test_inputs = [(0, 0), (0, 1), (1, 0), (1, 1)]
correct_outputs = [True, False, True, False]
outputs = []

# Generate and check output
for test_input, correct_output in zip(test_inputs, correct_outputs):
    linear_combination = weight1 * test_input[0] + weight2 * test_input[1] + bias
    output = int(linear_combination >= 0)
    is_correct_string = 'Yes' if output == correct_output else 'No'
    outputs.append([test_input[0], test_input[1], linear_combination, output, is_correct_string])

# Print output
num_wrong = len([output[4] for output in outputs if output[4] == 'No'])
output_frame = pd.DataFrame(outputs, columns=['Input 1', '  Input 2', '  Linear Combination', '  Activation Output', '  Is Correct'])
if not num_wrong:
    print('Nice!  You got it all correct.\n')
else:
    print('You got {} wrong.  Keep trying!\n'.format(num_wrong))
print(output_frame.to_string(index=False))

Nice!  You got it all correct.

Input 1    Input 2    Linear Combination    Activation Output   Is Correct
      0          0                  0.00                    1          Yes
      0          1                 -0.26                    0          Yes
      1          0                  0.25                    1          Yes
      1          1                 -0.01                    0          Yes


# Perceptron Algorithm

In [55]:
import numpy as np
# Setting the random seed, feel free to change it and see different solutions.
np.random.seed(42)

def stepFunction(t):
    if t >= 0:
        return 1
    return 0

def prediction(X, W, b):
    return stepFunction((np.matmul(X,W)+b)[0])

# TODO: Fill in the code below to implement the perceptron trick.
# The function should receive as inputs the data X, the labels y,
# the weights W (as an array), and the bias b,
# update the weights and bias W, b, according to the perceptron algorithm,
# and return W and b.
#def perceptronStep(X, y, W, b, learn_rate = 0.01):
#    # Fill in code
#    return W, b
    
# This function runs the perceptron algorithm repeatedly on the dataset,
# and returns a few of the boundary lines obtained in the iterations,
# for plotting purposes.
# Feel free to play with the learning rate and the num_epochs,
# and see your results plotted below.
def trainPerceptronAlgorithm(X, y, learn_rate = 0.01, num_epochs = 25):
    x_min, x_max = min(X.T[0]), max(X.T[0])
    y_min, y_max = min(X.T[1]), max(X.T[1])
    W = np.array(np.random.rand(2,1))
    b = np.random.rand(1)[0] + x_max
    # These are the solution lines that get plotted below.
    boundary_lines = []
    for i in range(num_epochs):
        # In each epoch, we apply the perceptron step.
        W, b = perceptronStep(X, y, W, b, learn_rate)
        boundary_lines.append((-W[0]/W[1], -b/W[1]))
    return boundary_lines


In [54]:
def perceptronStep(X, y, W, b, learn_rate = 0.01):
    for i in range(len(X)):
        y_hat = prediction(X[i],W,b)
        if y[i]-y_hat == 1:
            W[0] += X[i][0]*learn_rate
            W[1] += X[i][1]*learn_rate
            b += learn_rate
        elif y[i]-y_hat == -1:
            W[0] -= X[i][0]*learn_rate
            W[1] -= X[i][1]*learn_rate
            b -= learn_rate
    return W, b


In [65]:
import pandas as pd
import numpy as np

# Load dataset
filename = 'perceptron-data.csv'
df = pd.read_csv(filename, delimiter=',', header=None)
df.sample(5)



0        1  2
80  0.56846  0.74060  0
59  0.71442  0.76680  0
6   0.27527  0.33223  1
12  0.25644  0.42624  1
40  0.37095  0.38809  1

In [70]:
# Split
X = np.array(df.iloc[:,:-1])
y = np.array(df.iloc[:,-1])

trainPerceptronAlgorithm(X, y, learn_rate = 0.01, num_epochs = 25)

[(array([-0.49765709]), array([-3.82682049])),
 (array([-1.97786727]), array([3.50388692])),
 (array([-1.51086497]), array([1.26511216])),
 (array([-1.46106265]), array([1.17742037])),
 (array([-1.42113323]), array([1.16485855])),
 (array([-1.39002449]), array([1.15875514])),
 (array([-1.35924005]), array([1.15271535])),
 (array([-1.32877487]), array([1.1467382])),
 (array([-1.28726789]), array([1.06751541])),
 (array([-1.25128883]), array([1.05675318])),
 (array([-1.21602798]), array([1.04620578])),
 (array([-1.18146405]), array([1.03586685])),
 (array([-1.14757657]), array([1.02573026])),
 (array([-1.1203463]), array([1.02079866])),
 (array([-1.09337661]), array([1.01591424])),
 (array([-1.06666378]), array([1.01107635])),
 (array([-1.05159899]), array([1.00963413])),
 (array([-1.02411527]), array([1.00163602])),
 (array([-0.99468242]), array([0.93337733])),
 (array([-0.96452273]), array([0.92478496])),
 (array([-0.93491326]), array([0.91634936])),
 (array([-0.90583908]), array([0.90